server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server #eureka实例主机名
  client:
    fetch-registry: false          #不从eureka上获取注册信息
    register-with-eureka: false   #不把自己注册到eureka上
    service-url:
      defaultZone: http://localhost:8761/eureka/